# tasks for Red Hat Familly
---
#- name: Disable SELinux
#  selinux:
#    state: disabled
#  when: ansible_selinux.status == 'enabled'

- name: "Add Percona yum repository"
  yum:
    name: http://www.percona.com/redir/downloads/percona-release/redhat/0.0-1/percona-release-0.0-1.x86_64.rpm
    state: present
#  become: true
#  become_user: cluster

- name: repository installation
  yum_repository:
    file: "{{ xtradb_repo_filename }}" 
    name: "{{ xtradb_repo_name }}"
    description: "{{ xtradb_repo_desc }}"
    baseurl: "{{ xtradb_repo_baseurl }}"
    gpgkey: "{{ xtradb_repo_gpgkey }}"
    gpgcheck: "{{ xtradb_repo_gpgcheck }}"


...
