---
# tasks file for redis

  - name: Install Redis on Debian
    include: debian.yml
    when: ansible_os_family == 'Debian'

  - name: Install Redis on RedHat
    include: redhat.yml
    when: ansible_os_family == 'RedHat'
  

  - name: Configure Redis Common tasks
    include: config.yml





