---
- hosts: percona 
  gather_facts: true 
#  become_user: cluster
  become: true
#  become_method: sudo

  roles:
    - role: xtradb-percona-cluster 
      xtradb_cluster_name: "my-xtercluster"
      xtradb_sst_user: sstuser
      xtradb_sst_password: s3cr3t
      xtradb_root_password: root 

      xtradb_nodes_group: "percona"
      xtradb_bind_interface: eth1
