---
# tasks file for php7
- name: Install php7 on debian or derivates
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - php7.2
    - php7.2-cgi
    - php7.2-cli
    - php7.2-common
    - php7.2-fpm
    - php7.2-intl
    - php7.2-mysql
    - php7.2-mbstring
    - php7.2-xml
    - php7.2-ldap
    - php7.2-gd
    - php7.2-bcmath
    - php7.2-dev
    - php7.2-fpm
    - libpcre3-dev
    - php7.2-curl
    - php7.2-json
    - php7.2-opcache
    - php7.2-soap
    - php7.2-zip
    - php-sqlite3
    - php-apcu
  when:
    ansible_distribution == 'Debian'
    or
    ansible_distribution == 'Ubuntu'
  notify:
    - enable php
