---
- name: Configure Apache.
  lineinfile:
    dest: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ apache_ports_configuration_items }}"
  notify: restart apache

- name: Add apache vhosts configuration.
  template:
    src: vhosts.conf.j2
    dest: "{{ apache_conf_path }}/{{ server_name }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
