---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define apache_packages.
  set_fact:
    apache_packages: "{{ apache_packages | list }}"
  when: apache_packages is not defined

- name: Install Apache.
  include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Configure Apache.
  include_tasks: "configure-{{ ansible_os_family }}.yml"

- name: Ensure Apache has start state and enabled on boot.
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: true
