---
- name: Update apt cache.
  apt: 
    update_cache: yes 
    cache_valid_time: 3600
  become: yes
  
- name: Ensure Apache is installed on Debian.
  apt: 
    name: "{{ apache_packages }}"
    state: present
  become: yes
